package:
  name: gertrude
  epoch: 0
  version: v0.1.0-dirty
  description: botten gertrude
  url: https://github.com/mt-inside/gertrude
  copyright:
    - paths:
        - "*"
      license: Apache-2.0
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - build-base
      - pkgconf
      - openssl-dev
      - rust
      - protobuf-dev
      - just
      - git
pipeline:
  - name: Build
    runs: |
      just build-ci
      mkdir -p "${{targets.destdir}}/usr/bin"
      mv "./target/release/gertrude" "${{targets.destdir}}/usr/bin"
