name: test

on: push

jobs:
  test:
    name: Lint and test
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Install tools
        run: just tools-install

      - name: Find tools
        run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - name: Lint & Test
        run: just test

      # For this to work, the repo needs setting up on Coveralls.io
      - name: Coveralls Upload
        uses: coverallsapp/github-action@v2
        with:
          file: target/debug/coverage/lcov
          format: lcov
          # Doesn't need a coveralls API key, cause it uses the ambient GH key to auth that way (coveralls is installed as a GH oauth app)
